### ISSUE TITLE
[Module Conflict] TokenLightCondition

### ISSUE THREAD

**Issue by txm3278** [Saibot393/perceptive#3]
https://github.com/Frstrm/TokenLightCondition

Posted over there too: https://github.com/Frstrm/TokenLightCondition/issues/58

With both of these modules active I get the following error:

`Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'object')
[Detected 5 packages: perceptive, lib-wrapper, wall-height, levels, tokenlightcondition]
    at 🎁ClockwiseSweepPolygon.prototype._testWallInclusion#perceptive (PeekingScript.js:176:158)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at ClockwiseSweepPolygon.testWallInclusion (patches.js:270:10)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁ClockwiseSweepPolygon.prototype._testWallInclusion#0 (libWrapper-wrapper.js:189:20)
    at collisionTest (foundry.js:34011:45)
    at Quadtree.getObjects (foundry.js:30478:55)
    at Quadtree.getObjects (foundry.js:30471:11)
    at Quadtree.getObjects (foundry.js:30471:11)
    at CanvasQuadtree.getObjects (foundry.js:30471:11)
    at ClockwiseSweepPolygon._getWalls (foundry.js:34012:34)
    at ClockwiseSweepPolygon._identifyEdges (foundry.js:48712:24)
    at ClockwiseSweepPolygon._testCollision (foundry.js:49153:10)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at ClockwiseSweepPolygon._testCollision (sightHandler.js:185:49)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁ClockwiseSweepPolygon.prototype._testCollision#0 (libWrapper-wrapper.js:189:20)
    at ClockwiseSweepPolygon.testCollision (foundry.js:34151:17)
    at Core.get_wall_collision (core.js:164:59)
    at Lighting.find_token_lighting (lighting.js:226:44)
    at Lighting.check_token_lighting (lighting.js:63:22)
    at Lighting.check_all_tokens_lightingRefresh (lighting.js:74:30)
    at processLightingRefresh (main.js:100:20)
    at Object.fn (main.js:57:14)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at EffectsCanvasGroup.refreshLighting (foundry.js:47640:11)
    at PerceptionManager.applyRenderFlags (foundry.js:50262:49)
    at #applyRenderFlags (foundry.js:27701:44)
    at nn.emit (index.js:89:1)
    at Dt.update (index.js:89:1)
    at Dt._tick (index.js:89:1)`

**Comment by Saibot393** [comment]
I just released v1.2.3 which should fix this error. I could however not replicate the error and therefore not verify the fix myself.

**Comment by txm3278** [comment]
Tested it and it's fixed, thanks!
